definitions:
  dao.AccessControl:
    properties:
      black_list:
        type: string
      clientip_flow_limit:
        type: integer
      id:
        type: integer
      open_auth:
        type: integer
      service_flow_limit:
        type: integer
      service_id:
        type: integer
      white_host_name:
        type: string
      white_list:
        type: string
    type: object
  dao.GrpcRule:
    properties:
      header_transfor:
        type: string
      id:
        type: integer
      port:
        type: integer
      service_id:
        type: integer
    type: object
  dao.HttpRule:
    properties:
      header_transfor:
        type: string
      id:
        type: integer
      need_https:
        type: integer
      need_strip_uri:
        type: integer
      need_websocket:
        type: integer
      rule:
        type: string
      rule_type:
        type: integer
      service_id:
        type: integer
      url_rewrite:
        type: string
    type: object
  dao.LoadBalance:
    properties:
      check_interval:
        type: integer
      check_method:
        type: integer
      check_timeout:
        type: integer
      forbid_list:
        type: string
      id:
        type: integer
      ip_list:
        type: string
      round_type:
        type: integer
      service_id:
        type: integer
      upstream_connect_timeout:
        type: integer
      upstream_header_timeout:
        type: integer
      upstream_idle_timeout:
        type: integer
      upstream_max_idle:
        type: integer
      weight_list:
        type: string
    type: object
  dao.ServiceDetail:
    properties:
      access_control:
        $ref: '#/definitions/dao.AccessControl'
      grpc:
        $ref: '#/definitions/dao.GrpcRule'
      http:
        $ref: '#/definitions/dao.HttpRule'
      info:
        $ref: '#/definitions/dao.ServiceInfo'
      load_balance:
        $ref: '#/definitions/dao.LoadBalance'
      tcp:
        $ref: '#/definitions/dao.TcpRule'
    type: object
  dao.ServiceInfo:
    properties:
      create_at:
        type: string
      id:
        type: integer
      is_delete:
        type: integer
      load_type:
        type: integer
      service_desc:
        type: string
      service_name:
        type: string
      update_at:
        type: string
    type: object
  dao.TcpRule:
    properties:
      id:
        type: integer
      port:
        type: integer
      service_id:
        type: integer
    type: object
  dto.AdminInfoOutput:
    properties:
      avatar:
        type: string
      id:
        type: integer
      introduction:
        type: string
      login_time:
        type: string
      name:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  dto.AdminLoginInput:
    properties:
      password:
        description: 管理员密码
        example: "123456"
        type: string
      user_name:
        description: 管理员用户名
        example: admin
        type: string
    required:
    - password
    - user_name
    type: object
  dto.AdminLoginOutput:
    properties:
      token:
        description: token
        example: token
        type: string
    type: object
  dto.ChangePwdInput:
    properties:
      password:
        description: 管理员密码
        example: "123456"
        type: string
    required:
    - password
    type: object
  dto.DemoInput:
    properties:
      age:
        example: 20
        type: integer
      name:
        example: 姓名
        type: string
      passwd:
        example: "123456"
        type: string
    required:
    - age
    - name
    - passwd
    type: object
  dto.ServiceAddHTTPInput:
    properties:
      black_list:
        description: 黑名单ip
        example: ""
        type: string
      clientip_flow_limit:
        description: 客户端ip限流
        example: 0
        minimum: 0
        type: integer
      header_transfor:
        description: header转换
        example: ""
        type: string
      ip_list:
        description: ip列表
        example: ""
        type: string
      need_https:
        description: 支持https
        example: 1
        maximum: 1
        minimum: 0
        type: integer
      need_strip_uri:
        description: 启用strip_uri
        example: 1
        maximum: 1
        minimum: 0
        type: integer
      need_websocket:
        description: 是否支持websocket
        example: 1
        maximum: 1
        minimum: 0
        type: integer
      open_auth:
        description: 关键词
        example: 1
        maximum: 1
        minimum: 0
        type: integer
      round_type:
        description: 轮询方式
        example: 0
        maximum: 3
        minimum: 0
        type: integer
      rule:
        description: 域名或者前缀
        example: ""
        type: string
      rule_type:
        description: 接入类型
        example: 1
        maximum: 1
        minimum: 0
        type: integer
      service_desc:
        description: 服务描述
        example: ""
        maxLength: 255
        minLength: 1
        type: string
      service_flow_limit:
        description: 服务端限流
        example: 0
        minimum: 0
        type: integer
      service_name:
        description: 服务名
        example: ""
        type: string
      upstream_connect_timeout:
        description: 建立连接超时, 单位s
        example: 0
        minimum: 0
        type: integer
      upstream_header_timeout:
        description: 获取header超时, 单位s
        example: 0
        minimum: 0
        type: integer
      upstream_idle_timeout:
        description: 链接最大空闲时间, 单位s
        example: 0
        minimum: 0
        type: integer
      upstream_max_idle:
        description: 最大空闲链接数
        example: 0
        minimum: 0
        type: integer
      url_rewrite:
        description: url重写功能
        example: ""
        type: string
      weight_list:
        description: 权重列表
        example: ""
        type: string
      white_list:
        description: 白名单ip
        example: ""
        type: string
    required:
    - ip_list
    - rule
    - service_desc
    - service_name
    - weight_list
    type: object
  dto.ServiceListItemOutput:
    properties:
      id:
        description: id
        type: integer
      load_type:
        description: 服务类型
        type: integer
      qpd:
        description: qpd
        type: integer
      qps:
        description: qps
        type: integer
      service_addr:
        description: 服务地址
        type: string
      service_desc:
        description: 服务描述
        type: string
      service_name:
        description: 服务名称
        type: string
      total_node:
        description: 节点数
        type: integer
    type: object
  dto.ServiceListOutput:
    properties:
      list:
        description: 列表
        items:
          $ref: '#/definitions/dto.ServiceListItemOutput'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  dto.ServiceUpdateHTTPInput:
    properties:
      black_list:
        description: 黑名单ip
        example: ""
        type: string
      clientip_flow_limit:
        description: 客户端ip限流
        example: 0
        minimum: 0
        type: integer
      header_transfor:
        description: header转换
        example: ""
        type: string
      id:
        description: 服务名
        example: 62
        minimum: 1
        type: integer
      ip_list:
        description: ip列表
        example: 127.0.0.1:80
        type: string
      need_https:
        description: 支持https
        example: 0
        maximum: 1
        minimum: 0
        type: integer
      need_strip_uri:
        description: 启用strip_uri
        example: 0
        maximum: 1
        minimum: 0
        type: integer
      need_websocket:
        description: 是否支持websocket
        example: 0
        maximum: 1
        minimum: 0
        type: integer
      open_auth:
        description: 关键词
        example: 0
        maximum: 1
        minimum: 0
        type: integer
      round_type:
        description: 轮询方式
        example: 0
        maximum: 3
        minimum: 0
        type: integer
      rule:
        description: 域名或者前缀
        example: /test_http_service_indb
        type: string
      rule_type:
        description: 接入类型
        example: 0
        maximum: 1
        minimum: 0
        type: integer
      service_desc:
        description: 服务描述
        example: test_http_service_indb
        maxLength: 255
        minLength: 1
        type: string
      service_flow_limit:
        description: 服务端限流
        example: 0
        minimum: 0
        type: integer
      service_name:
        description: 服务名
        example: test_http_service_indb
        type: string
      upstream_connect_timeout:
        description: 建立连接超时, 单位s
        example: 0
        minimum: 0
        type: integer
      upstream_header_timeout:
        description: 获取header超时, 单位s
        example: 0
        minimum: 0
        type: integer
      upstream_idle_timeout:
        description: 链接最大空闲时间, 单位s
        example: 0
        minimum: 0
        type: integer
      upstream_max_idle:
        description: 最大空闲链接数
        example: 0
        minimum: 0
        type: integer
      url_rewrite:
        description: url重写功能
        example: ""
        type: string
      weight_list:
        description: 权重列表
        example: "50"
        type: string
      white_list:
        description: 白名单ip
        example: ""
        type: string
    required:
    - id
    - ip_list
    - rule
    - service_desc
    - service_name
    - weight_list
    type: object
  middleware.Response:
    properties:
      data: {}
      errmsg:
        type: string
      errno:
        type: integer
      stack: {}
      trace_id: {}
    type: object
info:
  contact: {}
paths:
  /admin/admin_info:
    get:
      consumes:
      - application/json
      description: 管理员信息
      operationId: /admin/admin_info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      summary: 管理员信息
      tags:
      - 管理员接口
  /admin/change_pwd:
    post:
      consumes:
      - application/json
      description: 更改密码
      operationId: /admin/change_pwd
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePwdInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 管理员信息
      tags:
      - 管理员接口
  /admin_login/login:
    post:
      consumes:
      - application/json
      description: 管理员登录
      operationId: /admin_login/login
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: 管理员登录
      tags:
      - 管理员接口
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: 管理员退出
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 管理员退出
      tags:
      - 管理员接口
  /demo/bind:
    post:
      consumes:
      - application/json
      description: 测试数据绑定
      operationId: /demo/bind
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.DemoInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.DemoInput'
              type: object
      summary: 测试数据绑定
      tags:
      - 用户
  /service/service_add_http:
    post:
      consumes:
      - application/json
      description: 添加HTTP服务
      operationId: /service/service_add_http
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.ServiceAddHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 添加HTTP服务
      tags:
      - 服务管理
  /service/service_delete:
    get:
      consumes:
      - application/json
      description: 服务删除
      operationId: /service/service_delete
      parameters:
      - description: 服务ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 服务删除
      tags:
      - 服务管理
  /service/service_detail:
    get:
      consumes:
      - application/json
      description: 服务详情
      operationId: /service/service_detail
      parameters:
      - description: 服务ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dao.ServiceDetail'
              type: object
      summary: 服务详情
      tags:
      - 服务管理
  /service/service_list:
    get:
      consumes:
      - application/json
      description: 服务列表
      operationId: /service/service_list
      parameters:
      - description: 关键词
        in: query
        name: info
        type: string
      - description: 每页个数
        in: query
        name: page_size
        required: true
        type: integer
      - description: 当前页数
        in: query
        name: page_no
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ServiceListOutput'
              type: object
      summary: 服务列表
      tags:
      - 服务管理
  /service/service_update_http:
    post:
      consumes:
      - application/json
      description: 修改HTTP服务
      operationId: /service/service_update_http
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.ServiceUpdateHTTPInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 修改HTTP服务
      tags:
      - 服务管理
swagger: "2.0"
